import tkinter


nfl_teams = {
    1: {'Arizona Cardinals': 'Arizona-Cardinals-logo-vector.jpg'},
    2: {'Chicago Bears': 'chicago-bears-logo-vector.png'},
    3: {'Green Bay Packers': 'green-bay-packers-logo-vector.png'},
    4: {'New York Giants': 'new-york-giants-logo-vector.png'},
    5: {'Detroit Lions': 'detroit-lions-logo-vector-01.png'},
    6: {'Washington Redskins': 'washington-redskins-logo-vector.png'},
    7: {'Philadelphia Eagles': 'philadelphia-eagles-logo.png'},
    8: {'Pittsburgh Steelers': 'pittsburgh-steelers-logo-vector-01.png'},
    9: {'Los Angeles Rams': 'st-louis-rams-vector-logo.png'},
    10: {'San Francisco 49ers': 'san-francisco-49ers-logo-vector.png'},
    11: {'Cleveland Browns': 'cleveland-browns-logo-vector-download.jpg'},
    12: {'Indianapolis Colts': 'indianapolis-colts-logo-vector-download.jpg'},
    13: {'Dallas Cowboys': 'dallas-cowboys-logo-vector.png'},
    14: {'Kansas City Chiefs': 'kansas-city-chiefs-logo-vector-download.jpg'},
    15: {'Los Angeles Chargers': 'san-diego-chargers-logo-vector.png'},
    16: {'Denver Broncos': 'denver-broncos-logo-vector.png'},
    17: {'New York Jets': 'new-york-jets-logo-vector-01.png'},
    18: {'New England Patriots': 'new-england-patriots-logo-preview.png'},
    19: {'Oakland Raiders': 'oakland-raiders-logo-vector.png'},
    20: {'Tennessee Titans': 'tennessee-titans-logo-vector-download.jpg'},
    21: {'Buffalo Bills': 'buffalo-bills-logo-vector-01.png'},
    22: {'Minnesota Vikings': 'minnesota-vikings-logo-vector.png'},
    23: {'Atlanta Falcons': 'atlanta-falcons-logo-vector.png'},
    24: {'Miami Dolphins': 'miami-dolphins-vector-logo.png'},
    25: {'New Orleans Saints': 'new-orleans-saints-logo-vector.png'},
    26: {'Cincinnati Bengals': 'cincinnati-bengals-logo-vector-01.png'},
    27: {'Seattle Seahawks': 'seattle-seahawks-logo-vector.png'},
    28: {'Tampa Bay Buccaneers': 'tampa-bay-buccaneers-logo-vector.png'},
    29: {'Carolina Panthers': 'carolina-panthers-logo-vector.png'},
    30: {'Jacksonville Jaguars': 'jacksonville-jaguars-logo-vector-download.jpg'},
    31: {'Baltimore Ravens': 'baltimore-ravens-logo-vector-01.png'},
    32: {'Houston Texans': 'houston-texans-logo-vector.png'}
}
